### ISSUE TITLE
Query response

### ISSUE THREAD

**Issue by gigaga** [cidevant/react-resource#2]
Really good job!
This module is very great.
However, the response of query() is currently not resource object, so I have to instantiate a new resource manually.
For example :
```javascript
User.query().then((users)=> {
    if (users[0]) {
        let user1= users[0];
        user1.name='RENARD';
        user1.$update() // I can't do like it because user1 is not a resource object :(
    }
});
````

**Comment by cidevant** [comment]
Sorry for late response. 

What if your API will return `{items: [users], count: 0}` instead of `[users]`? 
How to create instances from different api responses?

**Comment by cidevant** [comment]
Version 2.0 is out. Solves this
